create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name varchar(140) not null,
  slug varchar(180) not null unique,
  parent_id bigint references public.categories(id),
  sort_order integer not null default 0,
  base_value double precision,
  created_at timestamptz not null default now()
);

create table if not exists public.category_attributes (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.categories(id) on delete cascade,
  name varchar(80) not null,
  input_type varchar(16) not null default 'select',
  options text[],
  required boolean not null default false,
  sort_order integer not null default 0
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name varchar(160) not null unique,
  channel varchar(48) not null default 'Direct',
  contact_person varchar(140),
  email varchar(180),
  phone varchar(48),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.items (
  id bigint generated by default as identity primary key,
  sku varchar(24),
  name varchar(220) not null,
  brand varchar(140),
  model varchar(140),
  category_id bigint references public.categories(id),
  attributes jsonb,
  color varchar(90),
  material varchar(140),
  dimensions varchar(140),
  grade varchar(1),
  checklist jsonb,
  photos jsonb,
  condition_notes text,
  acquisition_cost double precision not null default 0,
  refurb_cost double precision not null default 0,
  listed_price double precision,
  floor_price double precision,
  benchmark_price double precision,
  value_low double precision,
  value_high double precision,
  sold_price double precision,
  sold_channel varchar(80),
  status varchar(12) not null default 'intake',
  supplier_id bigint references public.suppliers(id),
  location varchar(90),
  intake_at timestamptz not null default now(),
  listed_at timestamptz,
  sold_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.price_events (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id) on delete cascade,
  kind varchar(24) not null,
  price double precision,
  note varchar(240),
  created_at timestamptz not null default now()
);

create table if not exists public.item_shares (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.items(id) on delete cascade,
  token varchar(32) not null unique,
  remarks text,
  offer_price double precision,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists items_category_id_idx on public.items(category_id);
create index if not exists items_supplier_id_idx on public.items(supplier_id);
create index if not exists price_events_item_id_idx on public.price_events(item_id);
create index if not exists item_shares_item_id_idx on public.item_shares(item_id);