-- ==============================================================================
-- POPULATE INVENTORY SEED SCRIPT (25 Diverse Items)
-- ==============================================================================
-- Run this directly in your Supabase SQL Editor.
-- Safe to re-run: items are keyed by SKU so duplicates won't be created.

BEGIN;

-- 1. Ensure schema compatibility for recently added features
ALTER TABLE public.items ALTER COLUMN status TYPE varchar(32);
ALTER TABLE public.items ADD COLUMN IF NOT EXISTS is_featured boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id bigint NOT NULL REFERENCES public.items(id) ON DELETE CASCADE,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  author_name varchar(140) NOT NULL,
  content text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 2. Seed / Ensure Suppliers Exist
INSERT INTO public.suppliers (name, channel, contact_person, email, phone)
VALUES
  ('Makati Office Liquidations', 'Liquidation', 'Dana Villanueva', 'dana@makatioliq.example', '+63 917 555 0184'),
  ('Cebu Corporate Surplus', 'Downsizing', 'RJ Ramos', 'rj@cebusurplus.example', '+63 32 555 0119'),
  ('Kapitolyo Auction House', 'Auction', 'Liza Mercado', 'liza@kapitolyoauc.example', '+63 917 555 0142'),
  ('GreenCycle Reuse Network', 'Lease return', 'Tomás Reyes', 'tomas@greencycle.example', '+63 917 555 0177'),
  ('Alabang Relocation Services', 'Direct', 'Ingrid Ocampo', 'ingrid@alabangreloc.example', '+63 917 555 0133'),
  ('UP Diliman Property Surplus', 'Institutional', 'Marcos Bellen', 'mbellen@upd-surplus.example', '+63 2 555 0160')
ON CONFLICT (name) DO NOTHING;

-- 3. Seed / Ensure Root Categories Exist
INSERT INTO public.categories (name, slug, parent_id, sort_order)
VALUES
  ('Seating', 'seating', null, 1),
  ('Desks & Workstations', 'desks', null, 2),
  ('Tables', 'tables', null, 3),
  ('Storage', 'storage', null, 4),
  ('Partitions & Screens', 'partitions', null, 5),
  ('Reception & Lounge', 'reception', null, 6)
ON CONFLICT (slug) DO NOTHING;

-- 4. Seed / Ensure Leaf Categories Exist with Base Reference Values
INSERT INTO public.categories (name, slug, parent_id, sort_order, base_value)
SELECT sub.name, sub.slug, parent.id, sub.sort_order, sub.base_value
FROM (VALUES
  ('Task Chairs', 'task-chairs', 'seating', 1, 52500),
  ('Executive Chairs', 'executive-chairs', 'seating', 2, 77000),
  ('Conference Chairs', 'conference-chairs', 'seating', 3, 23000),
  ('Lounge Chairs', 'lounge-chairs', 'seating', 4, 60500),
  ('Standing Desks', 'standing-desks', 'desks', 1, 49500),
  ('Executive Desks', 'executive-desks', 'desks', 2, 88000),
  ('Bench Desk Pods', 'bench-desks', 'desks', 3, 132000),
  ('Conference Tables', 'conference-tables', 'tables', 1, 99000),
  ('Training Tables', 'training-tables', 'tables', 2, 26500),
  ('Side Tables', 'side-tables', 'tables', 3, 14500),
  ('Filing Cabinets', 'filing-cabinets', 'storage', 1, 23000),
  ('Credenzas', 'credenzas', 'storage', 2, 49500),
  ('Acoustic Screens', 'acoustic-panels', 'partitions', 1, 28500),
  ('Sofas & Soft Seating', 'sofas', 'reception', 1, 104500)
) AS sub(name, slug, parent_slug, sort_order, base_value)
JOIN public.categories parent ON parent.slug = sub.parent_slug
ON CONFLICT (slug) DO NOTHING;

-- 5. Insert 25 Diverse Inventory Items
WITH item_data AS (
  SELECT * FROM (VALUES
    (
      'RF-0101',
      'Herman Miller Aeron Remastered (Size B)',
      'Herman Miller',
      'Aeron Remastered',
      'task-chairs',
      'Makati Office Liquidations',
      '{"Size":"B","Arms":"Fully adjustable","Mechanism":"PostureFit SL","Tilt":"Forward & Back"}'::jsonb,
      'Graphite',
      'Pellicle Mesh',
      '68 x 67 x 104 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Mesh clean with zero sagging or pulls","status":"pass"},
        {"category":"structure","key":"c2","label":"Alloy frame & 5-star base solid","status":"pass"},
        {"category":"function","key":"c3","label":"Tilt lock, forward tilt & PostureFit SL operate smoothly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Fully adjustable armpads present and firm","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T10:00:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T10:02:00Z"},
        {"slot":"after","label":"After cleaning","url":"/images/reference-furniture.svg","timestamp":"2026-09-03T14:30:00Z"}
      ]'::jsonb,
      'Executive suite return in immaculate condition. PostureFit SL lumbar support fully responsive.',
      18500.00, 500.00, 29500.00, 22500.00, 54000.00, 26000.00, 34000.00,
      null, null, 'listed', 'WH-A · Rack 01', true,
      now() - interval '14 days', now() - interval '12 days', null
    ),
    (
      'RF-0102',
      'Steelcase Leap V2 Ergonomic Chair',
      'Steelcase',
      'Leap V2',
      'task-chairs',
      'Alabang Relocation Services',
      '{"Arms":"4D Adjustable","Lumbar":"Height & Firmness","Mechanism":"LiveBack"}'::jsonb,
      'Black',
      'Fabric / Upholstery',
      '69 x 62 x 99 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Upholstery steam sanitized, zero snags","status":"pass"},
        {"category":"structure","key":"c2","label":"LiveBack frame flexible and supportive","status":"pass"},
        {"category":"function","key":"c3","label":"Variable back stop & upper back force glide effortlessly","status":"pass"},
        {"category":"completeness","key":"c4","label":"4D arm caps intact without scuffs","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-04T09:15:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-04T09:18:00Z"}
      ]'::jsonb,
      'Top-tier ergonomic support with deep seat slide and 4D arm tracking.',
      14000.00, 600.00, 24000.00, 17500.00, 48000.00, 22000.00, 28000.00,
      null, null, 'listed', 'WH-A · Rack 02', true,
      now() - interval '10 days', now() - interval '8 days', null
    ),
    (
      'RF-0103',
      'Herman Miller Embody Task Chair',
      'Herman Miller',
      'Embody',
      'task-chairs',
      'Makati Office Liquidations',
      '{"Back":"Pixelated Matrix","Arms":"Fully adjustable","Base":"Titanium"}'::jsonb,
      'Berry Blue',
      'Pixelated Matrix Back',
      '75 x 74 x 106 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Fabric clean, matrix spines free of blemishes","status":"pass"},
        {"category":"structure","key":"c2","label":"Titanium base pristine with no scratches","status":"pass"},
        {"category":"function","key":"c3","label":"Backfit adjustment dials smoothly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Width-adjustable arms click securely","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-05T11:20:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-05T11:25:00Z"}
      ]'::jsonb,
      'Stunning Berry Blue fabric on White/Titanium frame. Pressure distribution matrix verified 100%.',
      28000.00, 500.00, 45000.00, 34500.00, 82000.00, 40000.00, 52000.00,
      null, null, 'listed', 'Showroom · Bay 1', true,
      now() - interval '7 days', now() - interval '6 days', null
    ),
    (
      'RF-0104',
      'Haworth Zody Ergonomic Chair',
      'Haworth',
      'Zody',
      'task-chairs',
      'GreenCycle Reuse Network',
      '{"Lumbar":"PAL Asymmetric","Arms":"4D","Mechanism":"Synchro-tilt"}'::jsonb,
      'Fog',
      'Mesh & Molded Foam',
      '67 x 66 x 98 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Mesh in good condition; light cosmetic dust","status":"flag"},
        {"category":"structure","key":"c2","label":"Cast aluminum base solid with light surface scuffs","status":"pass"},
        {"category":"function","key":"c3","label":"Asymmetrical lumbar adjustments work properly","status":"pass"},
        {"category":"completeness","key":"c4","label":"All adjustment paddles and tension rings complete","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-12T13:00:00Z"}
      ]'::jsonb,
      'Queued for standard detailing and upholstery foam wash. Mechanical components verified intact.',
      9500.00, 800.00, 16500.00, 12000.00, 38000.00, 14500.00, 19500.00,
      null, null, 'for_cleaning', 'WH-B · Rack 01', false,
      now() - interval '3 days', null, null
    ),
    (
      'RF-0105',
      'Steelcase Gesture with Headrest',
      'Steelcase',
      'Gesture',
      'task-chairs',
      'Kapitolyo Auction House',
      '{"Headrest":"Integrated","Arms":"360 Degree","Core":"Synchronous"}'::jsonb,
      'Cogent Graphite',
      'Fabric / 360 Core',
      '68 x 60 x 112 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Fabric clean, small scuff on headrest hinge","status":"flag"},
        {"category":"structure","key":"c2","label":"Spine & core equalizer rock solid","status":"pass"},
        {"category":"function","key":"c3","label":"Core equalizer mimics spine natural curvature","status":"pass"},
        {"category":"completeness","key":"c4","label":"360-degree rotating arms fully operational","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-08T15:00:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-08T15:05:00Z"}
      ]'::jsonb,
      'Premium 360-degree articulating arms with headrest. Light scuff on rear lower shell.',
      22000.00, 750.00, 36000.00, 27000.00, 68000.00, 32000.00, 42000.00,
      null, null, 'listed', 'WH-A · Rack 03', false,
      now() - interval '18 days', now() - interval '15 days', null
    ),
    (
      'RF-0106',
      'Humanscale Diffrient World Mesh Chair',
      'Humanscale',
      'Diffrient World',
      'task-chairs',
      'Cebu Corporate Surplus',
      '{"Back":"Form-sensing mesh","Mechanism":"Weight-sensitive recline","Arms":"Height adjustable"}'::jsonb,
      'Pinstripe Black',
      'Form-Sensing Mesh',
      '66 x 63 x 100 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Mesh clean, no fraying along boundary edges","status":"pass"},
        {"category":"structure","key":"c2","label":"Tri-panel mesh backrest frame intact","status":"pass"},
        {"category":"function","key":"c3","label":"Mechanism-free recline uses body weight smoothly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Arm assemblies solid and height locks securely","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-06T14:10:00Z"}
      ]'::jsonb,
      'Minimalist design with self-adjusting recline. Ready in stock for listing.',
      8000.00, 350.00, 14500.00, 10200.00, 35000.00, 13000.00, 17000.00,
      null, null, 'in_stock', 'WH-B · Rack 02', false,
      now() - interval '9 days', null, null
    ),
    (
      'RF-0107',
      'Vitra ID Mesh Task Chair',
      'Vitra',
      'ID Mesh',
      'task-chairs',
      'UP Diliman Property Surplus',
      '{"Mechanism":"FlowMotion","Arms":"2D","Base":"Polished Aluminium"}'::jsonb,
      'Nero',
      'Technical Mesh',
      '68 x 68 x 110 cm',
      'C',
      '[
        {"category":"surface","key":"c1","label":"Seat fabric shows minor spot stain","status":"flag"},
        {"category":"structure","key":"c2","label":"Base and frame completely intact","status":"pass"},
        {"category":"function","key":"c3","label":"FlowMotion mechanism requires lubricated retuning","status":"fail"},
        {"category":"completeness","key":"c4","label":"Right armpad cap has edge nick","status":"flag"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-13T09:00:00Z"},
        {"slot":"detail","label":"Wear detail","url":"/images/reference-furniture.svg","timestamp":"2026-09-13T09:04:00Z"}
      ]'::jsonb,
      'Assigned to repair bench for FlowMotion cylinder calibration and cushion shampooing.',
      7000.00, 1800.00, 15000.00, 10500.00, 42000.00, 13000.00, 18000.00,
      null, null, 'for_refurbishing', 'Refurb · Bench 2', false,
      now() - interval '4 days', null, null
    ),
    (
      'RF-0108',
      'Herman Miller Eames Soft Pad EA217',
      'Herman Miller',
      'Eames EA217',
      'executive-chairs',
      'Makati Office Liquidations',
      '{"Upholstery":"Full-grain leather","Frame":"Polished aluminum","Tilt lock":"Yes"}'::jsonb,
      'Cognac Leather',
      'Leather & Polished Aluminum',
      '58 x 60 x 86 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Leather supple with beautiful patina, zero cracks","status":"pass"},
        {"category":"structure","key":"c2","label":"Polished aluminum side ribs and crossbars spotless","status":"pass"},
        {"category":"function","key":"c3","label":"Tilt mechanism and pneumatic lift whisper quiet","status":"pass"},
        {"category":"completeness","key":"c4","label":"Herman Miller authentic medallion badge intact","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-01T16:00:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-01T16:05:00Z"},
        {"slot":"after","label":"Conditioned leather","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T11:00:00Z"}
      ]'::jsonb,
      'Classic mid-century executive chair. Hand-conditioned Cognac Italian leather.',
      35000.00, 1200.00, 58000.00, 43000.00, 110000.00, 52000.00, 68000.00,
      null, null, 'listed', 'Showroom · Bay 1', true,
      now() - interval '22 days', now() - interval '20 days', null
    ),
    (
      'RF-0109',
      'Knoll Life Executive Chair',
      'Knoll',
      'Life',
      'executive-chairs',
      'Alabang Relocation Services',
      '{"Upholstery":"Leather seat with knit back","Base":"Brushed aluminum"}'::jsonb,
      'Slate Leather',
      'Leather & Knit Back',
      '66 x 66 x 103 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Leather seat clean with minor crease lines","status":"pass"},
        {"category":"structure","key":"c2","label":"Cast aluminum chassis and loop arms sturdy","status":"pass"},
        {"category":"function","key":"c3","label":"Auto-balancing tension and seat slider work well","status":"pass"},
        {"category":"completeness","key":"c4","label":"Arm pads intact and clean","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-07T11:00:00Z"}
      ]'::jsonb,
      'High-end design suitable for boardroom or private office. Ready in stock.',
      15000.00, 600.00, 26000.00, 19000.00, 55000.00, 23000.00, 31000.00,
      null, null, 'in_stock', 'WH-A · Rack 01', false,
      now() - interval '8 days', null, null
    ),
    (
      'RF-0110',
      'Steelcase Cobi Flexing Guest Chair',
      'Steelcase',
      'Cobi',
      'conference-chairs',
      'Cebu Corporate Surplus',
      '{"Frame":"5-Star Swivel","Shell":"Flexing top edge"}'::jsonb,
      'Nickel',
      'Flexing Polypropylene Shell',
      '60 x 57 x 87 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Shell and seat fabric clean without stains","status":"pass"},
        {"category":"structure","key":"c2","label":"Swivel base balanced and smooth","status":"pass"},
        {"category":"function","key":"c3","label":"Flexing backrest edge provides active ergonomics","status":"pass"},
        {"category":"completeness","key":"c4","label":"All glides and fasteners factory original","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-09T10:00:00Z"}
      ]'::jsonb,
      'Designed specifically for collaborative meetings and conference rooms.',
      4500.00, 350.00, 8800.00, 6000.00, 22000.00, 7500.00, 10500.00,
      null, null, 'listed', 'WH-B · Floor 04', false,
      now() - interval '15 days', now() - interval '13 days', null
    ),
    (
      'RF-0111',
      'Vitra HAL Tube Sled Conference Chair',
      'Vitra',
      'HAL Tube',
      'conference-chairs',
      'Kapitolyo Auction House',
      '{"Frame":"Tubular steel sled","Shell":"Polypropylene"}'::jsonb,
      'Basalt',
      'Polypropylene & Chrome Steel',
      '52 x 49 x 79 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Matte shell shows very faint surface rubbing","status":"pass"},
        {"category":"structure","key":"c2","label":"Chrome steel legs level and solid","status":"pass"},
        {"category":"function","key":"c3","label":"Stackable up to 6 units safely","status":"pass"},
        {"category":"completeness","key":"c4","label":"Floor protective plastic glides intact","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-08-20T14:00:00Z"}
      ]'::jsonb,
      'Jasper Morrison design for Vitra. Sold in batch to corporate design agency.',
      3000.00, 200.00, 6500.00, 4200.00, 16500.00, 5500.00, 7800.00,
      6200.00, 'Office outfitter', 'sold', 'WH-B · Floor 04', false,
      now() - interval '45 days', now() - interval '40 days', now() - interval '10 days'
    ),
    (
      'RF-0112',
      'Herman Miller Eames Lounge Chair & Ottoman',
      'Herman Miller',
      'Eames Lounge',
      'lounge-chairs',
      'Makati Office Liquidations',
      '{"Veneer":"Molded Walnut 7-ply","Upholstery":"Black leather"}'::jsonb,
      'Walnut / Black Leather',
      'Molded Walnut Veneer & Leather',
      '84 x 88 x 96 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Full-grain black leather plush with zero punctures","status":"pass"},
        {"category":"structure","key":"c2","label":"7-ply molded walnut shells free of hairline cracks","status":"pass"},
        {"category":"function","key":"c3","label":"Die-cast swivel mechanism rotates silently","status":"pass"},
        {"category":"completeness","key":"c4","label":"Matching ottoman with original shock mounts intact","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-01T09:00:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-01T09:05:00Z"},
        {"slot":"after","label":"Finished display","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T15:30:00Z"}
      ]'::jsonb,
      'Collector grade Charles & Ray Eames icon. Reserved for client viewing at BGC showroom.',
      90000.00, 2500.00, 145000.00, 110000.00, 280000.00, 135000.00, 170000.00,
      null, null, 'reserved', 'Showroom · Bay 1', true,
      now() - interval '25 days', now() - interval '22 days', null
    ),
    (
      'RF-0113',
      'Steelcase Coalesse SW_1 Lounge Chair',
      'Steelcase',
      'SW_1 Lounge',
      'lounge-chairs',
      'GreenCycle Reuse Network',
      '{"Base":"4-star cast aluminum","Return-swivel":"Yes"}'::jsonb,
      'Nutmeg / White Shell',
      'Wool Blend Knit & Cast Aluminum',
      '76 x 81 x 74 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Wool knit cover clean with faint wear on arm crest","status":"pass"},
        {"category":"structure","key":"c2","label":"Cast aluminum white shell and base spotless","status":"pass"},
        {"category":"function","key":"c3","label":"Auto return-to-center swivel mechanism works perfectly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Integrated tablet accessory mount blank intact","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-05T16:00:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-05T16:05:00Z"}
      ]'::jsonb,
      'Collaborative lounge seating with wide seat pan and breathable open back design.',
      19000.00, 700.00, 32500.00, 24000.00, 72000.00, 29000.00, 38000.00,
      null, null, 'listed', 'Showroom · Bay 1', false,
      now() - interval '16 days', now() - interval '14 days', null
    ),
    (
      'RF-0114',
      'IKEA Bekant Motorized Sit/Stand Desk 160',
      'IKEA',
      'Bekant 160',
      'standing-desks',
      'Alabang Relocation Services',
      '{"Width":"160 cm","Motor":"Dual Motor","Controller":"Push button"}'::jsonb,
      'White / Silver Base',
      'Melamine & Powder-Coated Steel',
      '160 x 80 x 65-125 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Desktop surface clean; small minor mark on back edge","status":"flag"},
        {"category":"structure","key":"c2","label":"T-legs firm and level under full load","status":"pass"},
        {"category":"function","key":"c3","label":"Dual electric lift operates smoothly from 65 to 125 cm","status":"pass"},
        {"category":"completeness","key":"c4","label":"Cable management mesh net intact under desk","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-03T10:00:00Z"}
      ]'::jsonb,
      'Sturdy sit/stand workstation with generous 160x80cm surface and cable organizer.',
      9500.00, 400.00, 16500.00, 12000.00, 34000.00, 14000.00, 19000.00,
      null, null, 'listed', 'WH-B · Floor 04', false,
      now() - interval '20 days', now() - interval '18 days', null
    ),
    (
      'RF-0115',
      'Steelcase Migration SE Electric Standing Desk',
      'Steelcase',
      'Migration SE',
      'standing-desks',
      'Makati Office Liquidations',
      '{"Motor":"Dual German Linak","Controller":"4 Memory Presets"}'::jsonb,
      'Arctic White',
      'High-Pressure Laminate & Steel',
      '150 x 74 x 72-122 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"High-pressure laminate top flawless, zero scratches","status":"pass"},
        {"category":"structure","key":"c2","label":"Heavy gauge steel columns rock solid at maximum height","status":"pass"},
        {"category":"function","key":"c3","label":"Linak dual motors quiet with obstacle collision detection","status":"pass"},
        {"category":"completeness","key":"c4","label":"Digital display switch with 4 programmable presets","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-08T11:00:00Z"},
        {"slot":"back","label":"Rear / cables","url":"/images/reference-furniture.svg","timestamp":"2026-09-08T11:05:00Z"},
        {"slot":"after","label":"Cleaned surface","url":"/images/reference-furniture.svg","timestamp":"2026-09-09T13:00:00Z"}
      ]'::jsonb,
      'Commercial-grade motorized desk from multinational corporate headquarters relocation.',
      16000.00, 500.00, 27500.00, 20000.00, 58000.00, 24000.00, 32000.00,
      null, null, 'listed', 'WH-A · Rack 02', true,
      now() - interval '11 days', now() - interval '9 days', null
    ),
    (
      'RF-0116',
      'Fully Jarvis 150 Dual-Motor Bamboo Desk',
      'Fully',
      'Jarvis 150',
      'standing-desks',
      'Direct',
      '{"Top":"Sustainable Bamboo","Frame":"3-Stage Extended Legs"}'::jsonb,
      'Natural Bamboo / Black Frame',
      'Solid Bamboo Top & Steel Legs',
      '150 x 76 x 63-129 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Solid bamboo clear coated top without water rings or dents","status":"pass"},
        {"category":"structure","key":"c2","label":"Extended height 3-stage legs stable up to 129 cm","status":"pass"},
        {"category":"function","key":"c3","label":"Dual motor lifts 150 kg capacity easily","status":"pass"},
        {"category":"completeness","key":"c4","label":"OLED digital memory handset complete","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-08-15T09:00:00Z"}
      ]'::jsonb,
      'Eco-friendly solid bamboo standing desk. Sold to home-office software engineer.',
      14500.00, 350.00, 26500.00, 18500.00, 52000.00, 23000.00, 30000.00,
      26000.00, 'Direct buyer', 'sold', 'WH-A · Rack 03', false,
      now() - interval '60 days', now() - interval '55 days', now() - interval '12 days'
    ),
    (
      'RF-0117',
      'Knoll Reff L-Shaped Executive Desk Suite',
      'Knoll',
      'Reff Executive',
      'executive-desks',
      'Makati Office Liquidations',
      '{"Configuration":"L-Shaped with Return","Storage":"Integrated Pedestal"}'::jsonb,
      'Dark Walnut',
      'Architectural Wood Veneer',
      '183 x 91 x 74 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Walnut veneer clean with faint grain variation on return","status":"pass"},
        {"category":"structure","key":"c2","label":"Heavy timber joinery and solid base supports","status":"pass"},
        {"category":"function","key":"c3","label":"All ball-bearing drawer slides glide smoothly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Includes 2-drawer box/file pedestal with central lock key","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-04T15:00:00Z"},
        {"slot":"back","label":"Return view","url":"/images/reference-furniture.svg","timestamp":"2026-09-04T15:05:00Z"}
      ]'::jsonb,
      'Prestigious architectural wood executive workstation with generous modesty panels.',
      28000.00, 1500.00, 48000.00, 35500.00, 120000.00, 42000.00, 56000.00,
      null, null, 'listed', 'WH-B · Floor 04', false,
      now() - interval '19 days', now() - interval '17 days', null
    ),
    (
      'RF-0118',
      'Herman Miller Layout Studio 4-Pod Workstation',
      'Herman Miller',
      'Layout Studio 4',
      'bench-desks',
      'Cebu Corporate Surplus',
      '{"Seats":"4","Privacy screens":"Fabric dividers included","Power":"Central trough"}'::jsonb,
      'White Top / Charcoal Dividers',
      'Laminate, Acoustic Fabric & Steel Spine',
      '280 x 150 x 74 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Work surfaces clean; fabric screens vacuumed","status":"pass"},
        {"category":"structure","key":"c2","label":"Spine beam and intermediate legs rock solid","status":"pass"},
        {"category":"function","key":"c3","label":"Cable drop flaps hinge freely","status":"pass"},
        {"category":"completeness","key":"c4","label":"All 4 screen clamps, joiners and leveling glides present","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-10T11:00:00Z"}
      ]'::jsonb,
      'Complete 4-person benching system with central power tray and acoustic partition panels.',
      42000.00, 2000.00, 72000.00, 53000.00, 165000.00, 65000.00, 85000.00,
      null, null, 'in_stock', 'WH-B · Floor 04', false,
      now() - interval '6 days', null, null
    ),
    (
      'RF-0119',
      'Steelcase Convene Boat-Shape Conference Table',
      'Steelcase',
      'Convene Boat 300',
      'conference-tables',
      'Kapitolyo Auction House',
      '{"Seats":"10-12","Power modules":"Dual flip-top boxes","Shape":"Boat"}'::jsonb,
      'Natural Walnut',
      'Walnut Veneer & Integrated Power Trough',
      '300 x 127 x 74 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Walnut bookmatched veneer top in pristine condition","status":"pass"},
        {"category":"structure","key":"c2","label":"Sturdy drum bases provide massive stability","status":"pass"},
        {"category":"function","key":"c3","label":"Dual anodized aluminum power doors latch flush","status":"pass"},
        {"category":"completeness","key":"c4","label":"Wire management spine and leg conduits fully equipped","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T13:00:00Z"},
        {"slot":"detail","label":"Veneer grain","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T13:05:00Z"}
      ]'::jsonb,
      'Centerpiece conference table for 10-12 participants with discreet integrated AC/HDMI pass-throughs.',
      38000.00, 1200.00, 65000.00, 47000.00, 140000.00, 58000.00, 75000.00,
      null, null, 'listed', 'Showroom · Bay 1', true,
      now() - interval '21 days', now() - interval '19 days', null
    ),
    (
      'RF-0120',
      'IKEA Trotten Flip-Top Mobile Training Table',
      'IKEA',
      'Trotten Training',
      'training-tables',
      'UP Diliman Property Surplus',
      '{"Flip-top":"Yes","Casters":"Locking","Modesty panel":"No"}'::jsonb,
      'White / White A-Frame',
      'Melamine & Steel',
      '140 x 70 x 75 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Melamine top intact without chips","status":"pass"},
        {"category":"structure","key":"c2","label":"A-frame steel legs firm and straight","status":"pass"},
        {"category":"function","key":"c3","label":"Folding latch releases and locks properly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Lockable rubber casters roll freely","status":"pass"}
      ]'::jsonb,
      '[]'::jsonb,
      'Fresh intake batch of mobile nesting tables. Needs quick wipe-down and SKU tags.',
      4000.00, 0.00, null, 4900.00, 11500.00, 6000.00, 8500.00,
      null, null, 'intake', 'WH-A · Rack 03', false,
      now() - interval '1 day', null, null
    ),
    (
      'RF-0121',
      'Herman Miller Everywhere Round Side Table',
      'Herman Miller',
      'Everywhere 50',
      'side-tables',
      'Alabang Relocation Services',
      '{"Shape":"Round","Base":"4-star cast aluminum","Finish":"Studio White"}'::jsonb,
      'White / Polished Chrome',
      'Laminate & Cast Aluminum Base',
      '50 x 50 x 57 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Beveled top edge clean without staining","status":"pass"},
        {"category":"structure","key":"c2","label":"Cast column connection firm with no wobble","status":"pass"},
        {"category":"function","key":"c3","label":"Leveling glides adjust freely","status":"pass"},
        {"category":"completeness","key":"c4","label":"Original Herman Miller underside inspection stamp","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-07T14:00:00Z"}
      ]'::jsonb,
      'Versatile accent table designed by Dan Grabowski. Perfect companion for lounge seating.',
      4200.00, 250.00, 7900.00, 5400.00, 18000.00, 6800.00, 9200.00,
      null, null, 'listed', 'WH-A · Rack 01', false,
      now() - interval '13 days', now() - interval '11 days', null
    ),
    (
      'RF-0122',
      'Steelcase Universal Lateral 2-Drawer File',
      'Steelcase',
      'Universal Lateral 2D',
      'filing-cabinets',
      'GreenCycle Reuse Network',
      '{"Drawers":"2","Lock":"Key included","Orientation":"Lateral"}'::jsonb,
      'Merle Grey',
      'Heavy-Duty Cold-Rolled Steel',
      '91 x 46 x 71 cm',
      'B',
      '[
        {"category":"surface","key":"c1","label":"Powder-coat exterior has light rub mark on side","status":"pass"},
        {"category":"structure","key":"c2","label":"Carcass square and rigid without rack deformation","status":"pass"},
        {"category":"function","key":"c3","label":"Full-extension ball bearing suspensions glide smoothly","status":"pass"},
        {"category":"completeness","key":"c4","label":"Includes counterweight and working master key","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-08T16:00:00Z"}
      ]'::jsonb,
      'Heavy-duty secure document storage with interlock safety mechanism preventing multiple open drawers.',
      5500.00, 400.00, 10500.00, 7200.00, 24000.00, 9000.00, 12500.00,
      null, null, 'listed', 'WH-B · Rack 01', false,
      now() - interval '14 days', now() - interval '12 days', null
    ),
    (
      'RF-0123',
      'Knoll Calibre Sliding-Door Low Credenza',
      'Knoll',
      'Calibre 180',
      'credenzas',
      'Makati Office Liquidations',
      '{"Doors":"Sliding wood veneer","Length":"183 cm"}'::jsonb,
      'Medium Oak',
      'Oak Veneer & Satin Chrome Hardware',
      '183 x 50 x 66 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Oak veneer finished with zero scratches or sun fading","status":"pass"},
        {"category":"structure","key":"c2","label":"Base frame solid, internal shelf support sturdy","status":"pass"},
        {"category":"function","key":"c3","label":"Smooth bottom-track sliding door rollers silent","status":"pass"},
        {"category":"completeness","key":"c4","label":"All interior adjustable shelf pins and keys present","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-03T14:00:00Z"},
        {"slot":"back","label":"Interior view","url":"/images/reference-furniture.svg","timestamp":"2026-09-03T14:05:00Z"}
      ]'::jsonb,
      'Executive storage sideboard with architectural proportions. Soft-glide sliding doors.',
      18000.00, 800.00, 31000.00, 23000.00, 65000.00, 27000.00, 36000.00,
      null, null, 'listed', 'Showroom · Bay 1', false,
      now() - interval '17 days', now() - interval '15 days', null
    ),
    (
      'RF-0124',
      'Herman Miller Locale Freestanding Acoustic Screen',
      'Herman Miller',
      'Locale 150',
      'acoustic-panels',
      'Alabang Relocation Services',
      '{"Mount":"Freestanding timber base","Acoustic":"PET Recycled Core"}'::jsonb,
      'Oatmeal',
      'Acoustic PET Felt & Solid Maple Base',
      '150 x 8 x 140 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Acoustic felt face clean, completely odor & stain-free","status":"pass"},
        {"category":"structure","key":"c2","label":"Solid blonde maple timber foot provides stable balance","status":"pass"},
        {"category":"function","key":"c3","label":"High NRC rating absorbs open-plan reverberation","status":"pass"},
        {"category":"completeness","key":"c4","label":"Includes non-slip rubber floor pads","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-06T13:00:00Z"}
      ]'::jsonb,
      'Architectural visual & acoustic screen. Ideal for zoning open-plan team spaces.',
      7500.00, 300.00, 14000.00, 9800.00, 32000.00, 12000.00, 16500.00,
      null, null, 'listed', 'WH-A · Rack 02', false,
      now() - interval '12 days', now() - interval '10 days', null
    ),
    (
      'RF-0125',
      'Vitra Soft Modular 3-Seater Reception Sofa',
      'Vitra',
      'Soft Modular 3S',
      'sofas',
      'Makati Office Liquidations',
      '{"Seats":"3","Upholstery":"Premium Wool Blend","Legs":"Solid Oak"}'::jsonb,
      'Heather Grey Wool',
      'Wool Upholstery & Solid Oak Feet',
      '220 x 90 x 78 cm',
      'A',
      '[
        {"category":"surface","key":"c1","label":"Wool upholstery expertly deep cleaned with zero pilling","status":"pass"},
        {"category":"structure","key":"c2","label":"Internal steel chassis and spring suspension taut","status":"pass"},
        {"category":"function","key":"c3","label":"High density foam core retains crisp geometric shape","status":"pass"},
        {"category":"completeness","key":"c4","label":"All modular connector brackets included","status":"pass"}
      ]'::jsonb,
      '[
        {"slot":"front","label":"Front view","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T15:00:00Z"},
        {"slot":"back","label":"Back view","url":"/images/reference-furniture.svg","timestamp":"2026-09-02T15:05:00Z"},
        {"slot":"after","label":"Post-steam sanitized","url":"/images/reference-furniture.svg","timestamp":"2026-09-03T16:00:00Z"}
      ]'::jsonb,
      'Flagship reception sofa by Jasper Morrison. Elegant proportions with architectural presence.',
      38000.00, 1500.00, 68000.00, 49000.00, 160000.00, 60000.00, 80000.00,
      null, null, 'listed', 'Showroom · Bay 1', true,
      now() - interval '20 days', now() - interval '18 days', null
    )
  ) AS t(
    sku, name, brand, model, cat_slug, sup_name,
    attributes, color, material, dimensions, grade,
    checklist, photos, condition_notes,
    acquisition_cost, refurb_cost, listed_price, floor_price,
    benchmark_price, value_low, value_high,
    sold_price, sold_channel, status, location, is_featured,
    intake_at, listed_at, sold_at
  )
),
inserted_items AS (
  INSERT INTO public.items (
    sku, name, brand, model, category_id, supplier_id,
    attributes, color, material, dimensions, grade,
    checklist, photos, condition_notes,
    acquisition_cost, refurb_cost, listed_price, floor_price,
    benchmark_price, value_low, value_high,
    sold_price, sold_channel, status, location, is_featured,
    intake_at, listed_at, sold_at, created_at, updated_at
  )
  SELECT
    d.sku, d.name, d.brand, d.model, c.id, s.id,
    d.attributes, d.color, d.material, d.dimensions, d.grade,
    d.checklist, d.photos, d.condition_notes,
    d.acquisition_cost, d.refurb_cost, d.listed_price, d.floor_price,
    d.benchmark_price, d.value_low, d.value_high,
    d.sold_price, d.sold_channel, d.status, d.location, d.is_featured,
    d.intake_at, d.listed_at, d.sold_at, d.intake_at, COALESCE(d.sold_at, d.listed_at, d.intake_at)
  FROM item_data d
  JOIN public.categories c ON c.slug = d.cat_slug
  LEFT JOIN public.suppliers s ON s.name = d.sup_name
  WHERE NOT EXISTS (
    SELECT 1 FROM public.items existing WHERE existing.sku = d.sku
  )
  RETURNING id, sku, status, listed_price, acquisition_cost, sold_price, sold_channel, intake_at, listed_at, sold_at
)
-- 6. Insert Historical Price Events for the new items
, price_history AS (
  INSERT INTO public.price_events (item_id, kind, price, note, created_at)
  SELECT id, 'intake', acquisition_cost, 'Acquired during office inventory intake', intake_at
  FROM inserted_items
  UNION ALL
  SELECT id, 'listed', listed_price, 'Published to catalog for sale', listed_at
  FROM inserted_items
  WHERE listed_price IS NOT NULL AND listed_at IS NOT NULL
  UNION ALL
  SELECT id, 'sold', sold_price, COALESCE(sold_channel, 'Completed sale'), sold_at
  FROM inserted_items
  WHERE status = 'sold' AND sold_price IS NOT NULL AND sold_at IS NOT NULL
)
-- 7. Seed Reviews for Featured / Sold Items
INSERT INTO public.reviews (item_id, rating, author_name, content, created_at)
SELECT
  i.id, r.rating, r.author_name, r.content, i.listed_at + interval '2 days'
FROM inserted_items i
JOIN (VALUES
  ('RF-0101', 5, 'Marco D.', 'Exceptional condition! You can barely tell it was pre-owned. The PostureFit SL makes long workdays effortless.'),
  ('RF-0101', 5, 'Bea A.', 'Top notch quality control. Everything functions like brand new, highly recommended.'),
  ('RF-0102', 5, 'Patricia S.', 'Smooth viewing and pickup in Muntinlupa. Exactly as described in the condition checklist.'),
  ('RF-0103', 5, 'Liza T.', 'Superb value compared to brand new retail! The berry blue matrix back looks stunning in person.'),
  ('RF-0105', 4, 'Rafael C.', 'Very solid piece. Minor scuff on the base as clearly noted in the inspection photos, but mechanically 100% flawless.'),
  ('RF-0108', 5, 'Carlo M.', 'The leather patina on this Eames soft pad is gorgeous. Our boardroom looks first-class.'),
  ('RF-0111', 4, 'Kenneth L.', 'Sturdy Vitra chairs. The team assisted with loading into our van during warehouse release.'),
  ('RF-0115', 5, 'Adrian V.', 'The Linak dual motors are silent and smooth. Great upgrade from manual desks.'),
  ('RF-0116', 5, 'Stephanie G.', 'Bamboo finish is top quality. Transaction was super seamless.'),
  ('RF-0119', 5, 'David Tan', 'Impressive conference table. Integrated power outlets made wiring our Zoom Rooms super clean.'),
  ('RF-0125', 5, 'Monica R.', 'Clients constantly compliment this Vitra sofa in our reception lounge. Pristine upholstery condition.')
) AS r(sku, rating, author_name, content) ON r.sku = i.sku;

COMMIT;

-- Verify inserted items
SELECT
  id, sku, name, grade, status, listed_price, location, is_featured
FROM public.items
WHERE sku LIKE 'RF-01%'
ORDER BY sku;
